//ScanTrac Side View Source File
#if !defined(AFX_MAPISESSION_H__B3B76E92_B29C_11D5_AEAB_00500466E305__INCLUDED_)
#define AFX_MAPISESSION_H__B3B76E92_B29C_11D5_AEAB_00500466E305__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CMapiSession wrapper class

class CMapiSession : public CWnd
{
protected:
	DECLARE_DYNCREATE(CMapiSession)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x20c62ca0, 0x15da, 0x101b, { 0xb9, 0xa8, 0x44, 0x45, 0x53, 0x54, 0x0, 0x0 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = false,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	BOOL GetDownLoadMail();
	void SetDownLoadMail(BOOL bNewValue);
	BOOL GetLogonUI();
	void SetLogonUI(BOOL bNewValue);
	BOOL GetNewSession();
	void SetNewSession(BOOL bNewValue);
	short GetAction();
	void SetAction(short nNewValue);
	long GetSessionID();
	void SetSessionID(long nNewValue);
	CString GetPassword();
	void SetPassword(LPCTSTR lpszNewValue);
	CString GetUserName_();
	void SetUserName(LPCTSTR lpszNewValue);
	void SignOn();
	void SignOff();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_MAPISESSION_H__B3B76E92_B29C_11D5_AEAB_00500466E305__INCLUDED_)
