//ScanTrac Side View Source File
#if !defined(AFX_MAPIMESSAGES_H__B3B76E91_B29C_11D5_AEAB_00500466E305__INCLUDED_)
#define AFX_MAPIMESSAGES_H__B3B76E91_B29C_11D5_AEAB_00500466E305__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CMapiMessages wrapper class

class CMapiMessages : public CWnd
{
protected:
	DECLARE_DYNCREATE(CMapiMessages)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid = { 0x20c62cab, 0x15da, 0x101b, { 0xb9, 0xa8, 0x44, 0x45, 0x53, 0x54, 0x0, 0x0 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName, LPCTSTR lpszWindowName, DWORD dwStyle, const RECT& rect, CWnd* pParentWnd, UINT nID, CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle, const RECT& rect, CWnd* pParentWnd, UINT nID, CFile* pPersist = NULL, BOOL bStorage = false, BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID, pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	CString GetAddressCaption();
	void SetAddressCaption(LPCTSTR lpszNewValue);
	short GetAddressEditFieldCount();
	void SetAddressEditFieldCount(short nNewValue);
	CString GetAddressLabel();
	void SetAddressLabel(LPCTSTR lpszNewValue);
	BOOL GetAddressModifiable();
	void SetAddressModifiable(BOOL bNewValue);
	BOOL GetAddressResolveUI();
	void SetAddressResolveUI(BOOL bNewValue);
	long GetAttachmentCount();
	void SetAttachmentCount(long nNewValue);
	long GetAttachmentIndex();
	void SetAttachmentIndex(long nNewValue);
	CString GetAttachmentName();
	void SetAttachmentName(LPCTSTR lpszNewValue);
	CString GetAttachmentPathName();
	void SetAttachmentPathName(LPCTSTR lpszNewValue);
	long GetAttachmentPosition();
	void SetAttachmentPosition(long nNewValue);
	short GetAttachmentType();
	void SetAttachmentType(short nNewValue);
	CString GetFetchMsgType();
	void SetFetchMsgType(LPCTSTR lpszNewValue);
	BOOL GetFetchSorted();
	void SetFetchSorted(BOOL bNewValue);
	BOOL GetFetchUnreadOnly();
	void SetFetchUnreadOnly(BOOL bNewValue);
	CString GetMsgConversationID();
	void SetMsgConversationID(LPCTSTR lpszNewValue);
	long GetMsgCount();
	void SetMsgCount(long nNewValue);
	CString GetMsgDateReceived();
	void SetMsgDateReceived(LPCTSTR lpszNewValue);
	CString GetMsgID();
	void SetMsgID(LPCTSTR lpszNewValue);
	long GetMsgIndex();
	void SetMsgIndex(long nNewValue);
	CString GetMsgNoteText();
	void SetMsgNoteText(LPCTSTR lpszNewValue);
	CString GetMsgOrigAddress();
	void SetMsgOrigAddress(LPCTSTR lpszNewValue);
	CString GetMsgOrigDisplayName();
	void SetMsgOrigDisplayName(LPCTSTR lpszNewValue);
	BOOL GetMsgRead();
	void SetMsgRead(BOOL bNewValue);
	BOOL GetMsgReceiptRequested();
	void SetMsgReceiptRequested(BOOL bNewValue);
	BOOL GetMsgSent();
	void SetMsgSent(BOOL bNewValue);
	CString GetRecipAddress();
	void SetRecipAddress(LPCTSTR lpszNewValue);
	long GetRecipCount();
	void SetRecipCount(long nNewValue);
	CString GetRecipDisplayName();
	void SetRecipDisplayName(LPCTSTR lpszNewValue);
	long GetRecipIndex();
	void SetRecipIndex(long nNewValue);
	short GetRecipType();
	void SetRecipType(short nNewValue);
	long GetSessionID();
	void SetSessionID(long nNewValue);
	CString GetMsgSubject();
	void SetMsgSubject(LPCTSTR lpszNewValue);
	CString GetMsgType();
	void SetMsgType(LPCTSTR lpszNewValue);
	short GetAction();
	void SetAction(short nNewValue);
	void Compose();
	void Copy();
	void Delete(const VARIANT& vObj);
	void Fetch();
	void Forward();
	void Reply();
	void ReplyAll();
	void ResolveName();
	void Save();
	void Show(const VARIANT& vDetails);
	void Send(const VARIANT& vDialog);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_MAPIMESSAGES_H__B3B76E91_B29C_11D5_AEAB_00500466E305__INCLUDED_)
